#!/bin/bash

# Function to process single-end reads
process_single_end() {
    input_file="$1"
    output_file="${input_file%_R1_trimmed.fq.gz}_129cas.bam"

    bowtie2 --end-to-end --no-mixed --no-discordant \
            -p 10 -X 1000 -x ~/genomes/129cas/129cas \
            -U "$input_file" \
        | samtools view -@ 10 -b -q 20 - \
        | samtools sort -@ 10 -n - \
        | samtools fixmate -r -m - - \
        | samtools sort -@ 10 - \
	| samtools markdup -@ 10 -r -s -S - "${input_file%_R1_trimmed.fq.gz}_nodup_129cas.bam"
    
    samtools sort -@ 10 -n -o "$output_file" "${input_file%_R1_trimmed.fq.gz}_nodup_129cas.bam"
    rm "${input_file%_R1_trimmed.fq.gz}_nodup_129cas.bam"
}
# Function to process paired-end reads
process_paired_end() {
    input_file="$1"
    output_file="${input_file%_R1_val_1.fq.gz}_129cas.bam"

    bowtie2 --end-to-end --no-mixed --no-discordant \
            -p 10 -X 1000 -x ~/genomes/129cas/129cas \
            -1 "$input_file" -2 "${input_file/R1_val_1/R2_val_2}" \
        | samtools view -@ 10 -b -q 20 - \
        | samtools sort -@ 10 -n - \
        | samtools fixmate -r -m - - \
        | samtools sort -@ 10 - \
        | samtools markdup -@ 10 -r -s -S - "${input_file%_R1_val_1.fq.gz}_nodup_129cas.bam"
    
    samtools sort -@ 10 -n -o "$output_file" "${input_file%_R1_val_1.fq.gz}_nodup_129cas.bam"
    rm "${input_file%_R1_val_1.fq.gz}_nodup_129cas.bam"
}

export -f process_single_end
export -f process_paired_end

# Process single-end and paired-end reads in parallel
find . -maxdepth 1 -type f \( -name "*_R1_trimmed.fq.gz" -o -name "*_R1_val_1.fq.gz" \) \
| xargs -I{} -P 2 -n 1 sh -c 'if [[ "{}" =~ "_R1_trimmed.fq.gz" ]]; then process_single_end "{}"; else process_paired_end "{}"; fi'

# Haplotype phase 129 and cas alleles
find . -maxdepth 1 -type f -name "*129cas.bam" | xargs -I {} -P 10 bash -c 'snpsplit --no_sort --snp_file ~/genomes/129cas/129cas_SNPs.txt {}'
